---
- name: Validar conexión Ansible-cliente
  hosts: all
  gather_facts: false
  tasks:
  
  - name: Ping
    ping:
  - name: Leer archivo hosts
    slurp:
      path: /etc/hosts
    register: contenido_hosts

  - name: Mostrar contenido del archivo hosts
    debug:
      var: contenido_hosts.content | b64decode
  - name: Mostrar mensaje
    debug:
      msg: "Este es un playbook de prueba desde Github"
  - name: Hello Message
    debug:
      msg: "Hello World! - POST CONSFIGURACIÓN"
  - name: install the latest version of Apache
    dnf:
      name: httpd
      state: latest
  - firewalld:
      service: http
      permanent: yes
      state: enabled
