---
- name: Validar conexión Ansible-cliente
  hosts: all
  gather_facts: false
  collections:
    - /root/.ansible/collections/ansible_collections
    - /usr/share/ansible/collections/ansible_collections
  tasks:
    - name: Ping
      ping:
    - name: Mostrar mensaje en pantalla
      debug:
        msg: "Este es un mensaje de ejemplo enviado desde Ansible."
        verbosity: 2 
    - name: Send notify to Telegram
#      community.general.telegram:
      telegram:
        token: '5932614782:AAEA21lWegXVjZz6E0te3IhNU9pPE7desxU'
        api_args:
          chat_id: -602288015
          parse_mode: "markdown"
          text: "Ping to host {{ inventory_hostname }} successful mi"
          disable_web_page_preview: true
          disable_notification: true
