---
- name: Validar conexión Ansible-cliente
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping
      ping:
    - name: Mostrar mensaje en pantalla
      debug:
        msg: "Este es un mensaje de ejemplo enviado desde Ansible."
        echo: yes
